spring:
  datasource:
    source:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://0.0.0.0:3307/test?autoReconnect=true
      username: root
      password: 1234
    replica:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://0.0.0.0:3308/test?autoReconnect=true
      username: root
      password: 1234


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  profiles:
    include: oauth
  data:
    redis:
      host: localhost
      port: 6379


  application:
    name: replicationTest

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      group-id: consumer_group01

topic:
  name: test-topic

logging:
  level:
    org.hibernate.SQL: debug
