spring:

  application:
    name: kafkaTest

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      group-id: consumer_group02

topic:
  name: test-topic
